language: ruby
rvm:
  - 2.1.2
services:
  - postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - RAILS_ENV=test rake db:migrate
